# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlterIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteringredient', models.ManyToManyField(related_name='id_ingridient_w_alter', to='search_page.AlterIngredient')),
                ('ingredient', models.ManyToManyField(related_name='id_ingridient_wo_alter', to='search_page.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='listingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_recipe', to='search_page.Recipe'),
        ),
        migrations.AddField(
            model_name='alteringredient',
            name='alternative',
            field=models.ManyToManyField(related_name='id_complimentary_ingredient', to='search_page.Ingredient'),
        ),
        migrations.AddField(
            model_name='alteringredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_ingredient', to='search_page.Ingredient'),
        ),
    ]
