# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alteringredient',
            options={'verbose_name': 'Заменяемые ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Список ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='listingredient',
            options={'verbose_name': 'Список ингредиентов в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт'},
        ),
        migrations.AlterField(
            model_name='listingredient',
            name='alteringredient',
            field=models.ManyToManyField(blank=True, related_name='id_ingridient_w_alter', to='search_page.AlterIngredient'),
        ),
    ]
